// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/andrietri/guest-registration/api/v1/registration"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitGuestRegistration(db *gorm.DB) registration.RegistrationController {
	registrationRepository := registration.ProviderRegistrationRepository(db)
	registrationService := registration.ProviderRegistrationService(registrationRepository)
	registrationController := registration.ProviderRegistrationController(registrationService)
	return registrationController
}
